code:
  - 20000   # 请求成功
  - 10001   # 内容已存在
  - 10002   # 用户名或密码错误
  - 10003   # 内容不存在
  - 10004   # token失效
  - 10005   # 删除失败
  - 10006   # 更新用户信息失败
  - 10007   # 信息不完整
  - 10008   # 账号被禁用
  - 50000   # 无权限
  - 50008   # 登录信息过期，请重新登录